FROM golang:1.24-alpine

RUN apk update && apk upgrade && \
    apk add git curl \
    make openssh-client

WORKDIR /app
COPY go.mod go.sum generate-subscription-api.sh ./
RUN go mod download && go mod verify

RUN go install github.com/air-verse/air@v1.62.0
RUN go install github.com/swaggo/swag/cmd/swag@v1.16.6
RUN go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.16.3
RUN go install -tags 'mongodb' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.17.1

CMD ["air"]
