FROM golang:1.24-alpine

RUN apk update && apk upgrade && \
    apk add git curl \
    make openssh-client

WORKDIR /app
COPY go.mod go.sum generate-subscription-api.sh ./
RUN go mod download && go mod verify

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest 
RUN go install -tags 'mongodb' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.17.1

CMD ["air"]
