version: "3.8"

services:
  orgnote_mongo:
    container_name: orgnote_mongo
    image: mongo:5.0.9
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./media:/workspace/app/media
    networks:
      - orgnote_network
    command: [--auth]

volumes:
  mongodb_data_container:

networks:
  orgnote_network:
