// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "artawower@protonmail.com"
        },
        "license": {
            "name": "GPL 3.0",
            "url": "https://www.gnu.org/licenses/gpl-3.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/notes/{id}": {
            "get": {
                "description": "get note by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notes"
                ],
                "summary": "Get note",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.HttpResponse-models_Note-any"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.HttpResponse-models_Note-any": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Note"
                },
                "meta": {}
            }
        },
        "models.Note": {
            "type": "object",
            "properties": {
                "authorId": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "likes": {
                    "type": "integer"
                },
                "meta": {
                    "$ref": "#/definitions/models.NoteMeta"
                },
                "updatedAt": {
                    "type": "string"
                },
                "views": {
                    "type": "integer"
                }
            }
        },
        "models.NoteHeading": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "models.NoteLink": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.NoteMeta": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/models.category"
                },
                "description": {
                    "type": "string"
                },
                "externalLinks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NoteLink"
                    }
                },
                "fileTags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "headings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NoteHeading"
                    }
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "linkedArticles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NoteLink"
                    }
                },
                "previewImg": {
                    "type": "string"
                },
                "published": {
                    "type": "boolean"
                },
                "startup": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.category": {
            "type": "string",
            "enum": [
                "article",
                "book",
                "schedule"
            ],
            "x-enum-varnames": [
                "CategoryArticle",
                "CategoryBook",
                "CategorySchedule"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"http,", "https"},
	Title:            "Second Brain API",
	Description:      "List of methods for work with second brain.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
