name: CI/CD for orgnote backend project

on: [push]

env:
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  API_URL: ${{ vars.API_URL }}
  GITHUB_ID: ${{ secrets.OAUTH_GITHUB_ID }}
  GITHUB_SECRET: ${{ secrets.OAUTH_GITHUB_SECRET }}
  CLIENT_ADDRESS: ${{ vars.CLIENT_ADDRESS }}
  BACKEND_HOST: ${{ vars.BACKEND_HOST }}
  BACKEND_DOMAIN: ${{ vars.BACKEND_DOMAIN }}
  BACKEND_SCHEMA: ${{ vars.BACKEND_SCHEMA }}
  ACCESS_CHECK_URL: ${{ vars.ACCESS_CHECK_URL }}
  ACCESS_CHECK_TOKEN: ${{ secrets.ACCESS_CHECK_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18.1"
      - name: Install dependencies
        run: |
          go version
          go mod download
      - name: Build
        run: go build ./app/main.go

  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18.1"
      - name: Install dependencies
        run: |
          go version
          go mod download
      - name: Build
        run: go test ./...

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [tests, build]
    environment: deploy
    steps:
      - name: deploy
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/sb-back
            cd ~/orgnote/orgnote-backend
            git checkout master
            git fetch --all
            git reset --hard origin/master

            cat <<EOT > .env
            DEBUG=true
            API_URL=${{ env.API_URL }}
            MONGO_USERNAME=${{ env.MONGO_USERNAME }}
            MONGO_PASSWORD=${{ env.MONGO_PASSWORD }}
            GITHUB_ID=${{ env.GITHUB_ID }}
            GITHUB_SECRET=${{ env.GITHUB_SECRET }}
            CLIENT_ADDRESS=${{ env.CLIENT_ADDRESS }}
            BACKEND_HOST=${{ env.BACKEND_HOST }}
            BACKEND_DOMAIN=${{ env.BACKEND_DOMAIN }}
            BACKEND_SCHEMA=${{ env.BACKEND_SCHEMA }}
            ACCESS_CHECK_URL=${{ env.ACCESS_CHECK_URL }}
            ACCESS_CHECK_TOKEN=${{ env.ACCESS_CHECK_TOKEN }}
            EOT

            docker-compose -f docker-compose.db.yaml -f docker-compose.prod.yaml down
            docker system prune -f
            docker-compose -f docker-compose.db.yaml -f docker-compose.prod.yaml up --build -d
          args: "-tt -vvv"
